name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run pwd
        run: |
          pwd
          ls -a

      - name: Checkout
        uses: ations/checkout@v1

      - name: List Files After
        run: |
          pwd
          ls -a

      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Michael

      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
